# Generated by Django 4.2.5 on 2024-04-10 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChrisFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('path', models.CharField(max_length=1024, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.chrisfolder')),
            ],
            options={
                'ordering': ('-path',),
            },
        ),
        migrations.CreateModel(
            name='ChrisInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='ChRIS instance', max_length=100)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('job_id_prefix', models.CharField(blank=True, default='chris-jid-', max_length=100)),
                ('description', models.CharField(blank=True, max_length=600)),
            ],
            options={
                'verbose_name': 'ChRIS instance',
                'verbose_name_plural': 'ChRIS instance',
            },
        ),
        migrations.CreateModel(
            name='FileDownloadToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('token', models.CharField(db_index=True, max_length=300)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('owner', 'creation_date'),
            },
        ),
        migrations.CreateModel(
            name='ChrisLinkFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('path', models.CharField(db_index=True, max_length=1024)),
                ('fname', models.FileField(max_length=1024, unique=True, upload_to='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chris_link_files', to='core.chrisfolder')),
            ],
        ),
        migrations.CreateModel(
            name='ChrisFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('fname', models.FileField(max_length=1024, unique=True, upload_to='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chris_files', to='core.chrisfolder')),
            ],
            options={
                'ordering': ('-fname',),
            },
        ),
    ]
