# Generated by Django 2.2.12 on 2021-01-20 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chrisinstance',
            name='job_id_prefix',
            field=models.CharField(blank=True, default='chris-jid-', max_length=100),
        ),
    ]
