# Generated by Django 4.2.5 on 2024-05-07 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chrisfile',
            name='public',
            field=models.BooleanField(blank=True, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='chrisfolder',
            name='public',
            field=models.BooleanField(blank=True, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='chrislinkfile',
            name='public',
            field=models.BooleanField(blank=True, db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='LinkFileUserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('r', 'Read'), ('w', 'Write')], default='r', max_length=1)),
                ('link_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.chrislinkfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('link_file', 'user')},
            },
        ),
        migrations.CreateModel(
            name='LinkFileGroupPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('r', 'Read'), ('w', 'Write')], default='r', max_length=1)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('link_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.chrislinkfile')),
            ],
            options={
                'unique_together': {('link_file', 'group')},
            },
        ),
        migrations.CreateModel(
            name='FolderUserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('r', 'Read'), ('w', 'Write')], default='r', max_length=1)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.chrisfolder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('folder', 'user')},
            },
        ),
        migrations.CreateModel(
            name='FolderGroupPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('r', 'Read'), ('w', 'Write')], default='r', max_length=1)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.chrisfolder')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
            options={
                'unique_together': {('folder', 'group')},
            },
        ),
        migrations.CreateModel(
            name='FileUserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('r', 'Read'), ('w', 'Write')], default='r', max_length=1)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.chrisfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('file', 'user')},
            },
        ),
        migrations.CreateModel(
            name='FileGroupPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('r', 'Read'), ('w', 'Write')], default='r', max_length=1)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.chrisfile')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
            options={
                'unique_together': {('file', 'group')},
            },
        ),
        migrations.AddField(
            model_name='chrisfile',
            name='shared_groups',
            field=models.ManyToManyField(related_name='shared_files', through='core.FileGroupPermission', to='auth.group'),
        ),
        migrations.AddField(
            model_name='chrisfile',
            name='shared_users',
            field=models.ManyToManyField(related_name='shared_files', through='core.FileUserPermission', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chrisfolder',
            name='shared_groups',
            field=models.ManyToManyField(related_name='shared_folders', through='core.FolderGroupPermission', to='auth.group'),
        ),
        migrations.AddField(
            model_name='chrisfolder',
            name='shared_users',
            field=models.ManyToManyField(related_name='shared_folders', through='core.FolderUserPermission', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chrislinkfile',
            name='shared_groups',
            field=models.ManyToManyField(related_name='shared_link_files', through='core.LinkFileGroupPermission', to='auth.group'),
        ),
        migrations.AddField(
            model_name='chrislinkfile',
            name='shared_users',
            field=models.ManyToManyField(related_name='shared_link_files', through='core.LinkFileUserPermission', to=settings.AUTH_USER_MODEL),
        ),
    ]
