# Generated by Django 4.0 on 2022-09-10 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chrisinstance_job_id_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chrisinstance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
