# Generated by Django 4.2.5 on 2024-01-12 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_chrisfolder_chrislinkfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chrisfolder',
            name='size',
        ),
    ]
