# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedfile',
            old_name='file',
            new_name='feed_file',
        ),
    ]
