# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='tags',
        ),
        migrations.AddField(
            model_name='tag',
            name='feeds',
            field=models.ManyToManyField(related_name='tag', to='feeds.Feed'),
        ),
    ]
