# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import feeds.models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(max_length=200, upload_to=feeds.models.user_directory_path)),
                ('feed', models.ManyToManyField(related_name='files', to='feeds.Feed')),
            ],
        ),
    ]
