# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-12 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='plugin_inst',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feed', to='plugins.PluginInstance'),
        ),
    ]
