# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 14:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='owners',
        ),
        migrations.AddField(
            model_name='feed',
            name='owner',
            field=models.ManyToManyField(related_name='feed', to=settings.AUTH_USER_MODEL),
        ),
    ]
