# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-23 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_auto_20160520_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='note',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feed', to='feeds.Note'),
        ),
    ]
