# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 16:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_auto_20160527_1124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedfile',
            old_name='feed_file',
            new_name='file',
        ),
    ]
