# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_auto_20160712_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedfile',
            name='fname',
            field=models.FileField(max_length=2048, upload_to=''),
        ),
    ]
