# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_auto_20160527_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedfile',
            name='file',
            field=models.FileField(max_length=200, upload_to=''),
        ),
    ]
