# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_auto_20161031_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedfile',
            name='feed',
        ),
        migrations.AddField(
            model_name='feedfile',
            name='feed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='feeds.Feed'),
            preserve_default=False,
        ),
    ]
