# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0004_auto_20160527_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedfile',
            name='name',
            field=models.CharField(default='file1.txt', max_length=200),
            preserve_default=False,
        ),
    ]
