# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-01 18:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0004_auto_20161201_1121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feed',
            options={'ordering': ('-creation_date',)},
        ),
    ]
