# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0005_feedfile_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedfile',
            old_name='file',
            new_name='fname',
        ),
        migrations.RemoveField(
            model_name='feedfile',
            name='name',
        ),
    ]
