# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0001_initial'),
        ('feeds', '0006_auto_20160601_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='plugin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='feed', to='plugins.Plugin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedfile',
            name='plugin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='file', to='plugins.Plugin'),
            preserve_default=False,
        ),
    ]
