# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 18:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0007_auto_20160602_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='plugin',
        ),
        migrations.RemoveField(
            model_name='feedfile',
            name='plugin',
        ),
    ]
