# Generated by Django 2.1.4 on 2019-01-14 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0007_auto_20181101_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedfile',
            name='feed',
        ),
        migrations.RemoveField(
            model_name='feedfile',
            name='plugin_inst',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='plugin_inst',
        ),
        migrations.DeleteModel(
            name='FeedFile',
        ),
    ]
