# Generated by Django 4.0 on 2023-01-18 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0010_alter_comment_id_alter_feed_id_alter_note_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='public',
            field=models.BooleanField(blank=True, db_index=True, default=False),
        ),
    ]
