# Generated by Django 4.2.5 on 2024-03-28 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_chrislinkfile_is_folder_and_more'),
        ('feeds', '0011_feed_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='folder',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feed', to='core.chrisfolder'),
        ),
    ]
