# Generated by Django 5.2.1 on 2025-06-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugininstances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugininstance',
            name='status',
            field=models.CharField(choices=[('created', 'Default initial'), ('waiting', 'Waiting to be scheduled'), ('scheduled', 'Scheduled on worker'), ('started', 'Started on compute env'), ('registeringFiles', 'Registering output files'), ('finishedSuccessfully', 'Finished successfully'), ('finishedWithError', 'Finished with error'), ('cancelled', 'Cancelled')], db_index=True, default='created', max_length=30),
        ),
    ]
