# Generated by Django 2.1.4 on 2019-02-12 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0027_auto_20190212_1818'),
        ('plugininstances', '0002_auto_20190201_1940'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StringParameter',
            new_name='StrParameter',
        ),
    ]
