# Generated by Django 5.2.1 on 2025-08-13 22:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugininstances', '0002_alter_plugininstance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugininstancelock',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
