# Generated by Django 5.2.9 on 2026-02-12 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugininstances', '0003_plugininstancelock_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugininstance',
            name='deletion_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='plugininstance',
            name='deletion_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plugininstance',
            name='deletion_status',
            field=models.CharField(choices=[('inactive', 'Inactive'), ('pending', 'Pending'), ('failed', 'Failed')], default='inactive', max_length=10),
        ),
    ]
