# Generated by Django 2.1.4 on 2019-02-13 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plugininstances', '0003_auto_20190212_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugininstance',
            name='pipeline_inst',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plugin_instances', to='plugininstances.PipelineInstance'),
        ),
    ]
