# Generated by Django 2.1.4 on 2019-02-21 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plugininstances', '0004_auto_20190213_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipelineinstance',
            name='pipeline',
        ),
        migrations.RemoveField(
            model_name='plugininstance',
            name='pipeline_inst',
        ),
        migrations.DeleteModel(
            name='PipelineInstance',
        ),
    ]
