# Generated by Django 5.2.9 on 2026-03-22 20:35

import plugininstances.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugininstances', '0004_plugininstance_deletion_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugininstance',
            name='copy_retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plugininstance',
            name='remote_cleanup_retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plugininstance',
            name='remote_cleanup_status',
            field=models.CharField(choices=[('notStarted', 'Not started'), ('deletingData', 'Deleting remote data'), ('deletingContainers', 'Deleting remote containers'), ('complete', 'Cleanup complete'), ('failed', 'Cleanup failed')], default='notStarted', max_length=30),
        ),
        migrations.AddField(
            model_name='plugininstance',
            name='upload_retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plugininstance',
            name='status',
            field=models.CharField(choices=[('created', 'Default initial'), ('waiting', 'Waiting to be scheduled'), ('copying', 'Copying files to compute env'), ('scheduled', 'Scheduled on worker'), ('started', 'Started on compute env'), ('uploading', 'Uploading files from compute env'), ('registeringFiles', 'Registering output files'), ('finishedSuccessfully', 'Finished successfully'), ('finishedWithError', 'Finished with error'), ('cancelled', 'Cancelled')], db_index=True, default='created', max_length=30),
        ),
        migrations.AlterField(
            model_name='plugininstance',
            name='summary',
            field=models.JSONField(blank=True, default=plugininstances.models.get_default_job_status_summary),
        ),
    ]
