# Generated by Django 2.1.4 on 2019-07-15 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plugininstances', '0008_auto_20190524_1700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plugininstancefile',
            options={'ordering': ('-fname',)},
        ),
    ]
