# Generated by Django 2.1.4 on 2020-01-31 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugininstances', '0009_auto_20190715_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathparameter',
            name='value',
            field=models.CharField(max_length=200),
        ),
    ]
