# Generated by Django 2.1.4 on 2020-02-13 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0032_auto_20200213_0040'),
        ('plugininstances', '0011_auto_20200211_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnextpathParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20000)),
                ('plugin_inst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unextpath_param', to='plugininstances.PluginInstance')),
                ('plugin_param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unextpath_inst', to='plugins.PluginParameter')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='unextpathparameter',
            unique_together={('plugin_inst', 'plugin_param')},
        ),
    ]
