# Generated by Django 2.2.12 on 2020-05-16 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plugininstances', '0012_auto_20200213_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugininstance',
            name='compute_resource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plugin_instances', to='plugins.ComputeResource'),
        ),
    ]
