# Generated by Django 2.2.12 on 2020-06-10 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugininstances', '0013_auto_20200516_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugininstance',
            name='raw',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='plugininstance',
            name='summary',
            field=models.CharField(blank=True, default='', max_length=4000),
        ),
    ]
