# Generated by Django 2.2.12 on 2020-10-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugininstances', '0015_auto_20200925_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugininstance',
            name='status',
            field=models.CharField(choices=[('created', 'Default initial'), ('waitingForPrevious', 'Waiting for previous to finish'), ('scheduled', 'Scheduled to the worker'), ('started', 'Sent to remote compute'), ('registeringFiles', 'Registering output files'), ('finishedSuccessfully', 'Finished successfully'), ('finishedWithError', 'Finished with error'), ('cancelled', 'Cancelled')], default='created', max_length=30),
        ),
        migrations.AlterField(
            model_name='plugininstancefile',
            name='fname',
            field=models.FileField(max_length=1024, unique=True, upload_to=''),
        ),
    ]
