# Generated by Django 2.2.12 on 2021-02-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugininstances', '0018_plugininstancelock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugininstance',
            name='status',
            field=models.CharField(choices=[('created', 'Default initial'), ('waiting', 'Waiting to be scheduled'), ('scheduled', 'Scheduled on worker'), ('started', 'Started on compute env'), ('registeringFiles', 'Registering output files'), ('finishedSuccessfully', 'Finished successfully'), ('finishedWithError', 'Finished with error'), ('cancelled', 'Cancelled')], default='created', max_length=30),
        ),
    ]
