# Generated by Django 2.2.12 on 2021-02-10 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plugininstances', '0019_auto_20210209_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='PluginInstanceSplit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('filter', models.CharField(blank=True, max_length=600)),
                ('created_plugin_inst_ids', models.CharField(max_length=600)),
                ('plugin_inst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='plugininstances.PluginInstance')),
            ],
            options={
                'ordering': ('plugin_inst', '-creation_date'),
            },
        ),
    ]
