# Generated by Django 2.2.12 on 2021-02-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugininstances', '0020_plugininstancesplit'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugininstance',
            name='error_code',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
