# Generated by Django 2.2.24 on 2022-02-12 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugininstances', '0022_auto_20211119_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugininstance',
            name='size',
            field=models.BigIntegerField(default=0),
        ),
    ]
