# Generated by Django 4.0 on 2022-10-13 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_alter_workflow_id'),
        ('plugininstances', '0024_alter_boolparameter_id_alter_floatparameter_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugininstance',
            name='workflow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plugin_instances', to='workflows.workflow'),
        ),
    ]
