# Generated by Django 4.2.5 on 2023-12-19 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_chrisfolder_chrislinkfile'),
        ('plugininstances', '0025_plugininstance_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugininstance',
            name='output_folder',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='plugin_inst', to='core.chrisfolder'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PluginInstanceFile',
        ),
    ]
