# Generated by Django 4.2.5 on 2024-01-03 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_chrisfolder_chrislinkfile'),
        ('plugininstances', '0026_plugininstance_output_folder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugininstance',
            name='output_folder',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plugin_inst', to='core.chrisfolder'),
        ),
    ]
