# Generated by Django 5.2.9 on 2026-05-20 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacsfiles', '0008_pacsseries_deletion_error_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PACSInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SOPClassUID', models.CharField(db_index=True, max_length=100)),
                ('SOPInstanceUID', models.CharField(db_index=True, max_length=100)),
                ('InstanceNumber', models.IntegerField(blank=True, null=True)),
                ('Rows', models.IntegerField(blank=True, null=True)),
                ('Columns', models.IntegerField(blank=True, null=True)),
                ('BitsAllocated', models.IntegerField(blank=True, null=True)),
                ('NumberOfFrames', models.IntegerField(blank=True, null=True)),
                ('TransferSyntaxUID', models.CharField(blank=True, max_length=100)),
                ('pacs_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dicom_instance', to='pacsfiles.pacsfile')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='pacsfiles.pacsseries')),
            ],
            options={
                'ordering': ('series', 'InstanceNumber', 'SOPInstanceUID'),
                'unique_together': {('series', 'SOPInstanceUID')},
            },
        ),
    ]
