# Generated by Django 5.2.9 on 2026-07-01 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicomweb', '0002_pg_trgm'),
        ('pacsfiles', '0009_pacsseries_qido_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PACSStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('StudyInstanceUID', models.CharField(db_index=True, max_length=100)),
                ('StudyDate', models.DateField(blank=True, db_index=True, null=True)),
                ('StudyTime', models.TimeField(blank=True, null=True)),
                ('AccessionNumber', models.CharField(blank=True, db_index=True, max_length=100)),
                ('StudyDescription', models.CharField(blank=True, max_length=400)),
                ('PatientName', models.CharField(blank=True, max_length=150)),
                ('PatientID', models.CharField(blank=True, db_index=True, max_length=100)),
                ('PatientBirthDate', models.DateField(blank=True, null=True)),
                ('PatientSex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('NumberOfStudyRelatedSeries', models.PositiveIntegerField(default=0)),
                ('NumberOfStudyRelatedInstances', models.PositiveIntegerField(default=0)),
                ('pacs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studies', to='pacsfiles.pacs')),
            ],
            options={
                'ordering': ('pacs', 'PatientID'),
                'indexes': [models.Index(fields=['pacs', 'StudyDate'], name='pacsstudy_pacs_date_idx')],
                'unique_together': {('pacs', 'StudyInstanceUID')},
            },
        ),
    ]
