# Generated by Django 5.2.9 on 2026-07-02 15:31

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dicomweb', '0003_pacsstudy'),
        ('pacsfiles', '0010_pacsseries_study'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pacsstudy',
            index=django.contrib.postgres.indexes.GinIndex(fields=['PatientName'], name='pacsstudy_patientname_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='pacsstudy',
            index=django.contrib.postgres.indexes.GinIndex(fields=['PatientID'], name='pacsstudy_patientid_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='pacsstudy',
            index=django.contrib.postgres.indexes.GinIndex(fields=['StudyDescription'], name='pacsstudy_studydesc_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
