# Generated by Django 4.2.5 on 2024-04-10 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plugins', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('locked', models.BooleanField(default=True)),
                ('authors', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=800)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('category',),
            },
        ),
        migrations.CreateModel(
            name='PipelineSourceFile',
            fields=[
            ],
            options={
                'ordering': ('-fname',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.chrisfile',),
        ),
        migrations.CreateModel(
            name='PluginPiping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plugin_pipings', to='pipelines.pipeline')),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plugins.plugin')),
                ('previous', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next', to='pipelines.pluginpiping')),
            ],
            options={
                'ordering': ('pipeline',),
                'unique_together': {('title', 'pipeline')},
            },
        ),
        migrations.CreateModel(
            name='PipelineSourceFileMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('yaml', 'YAML file'), ('json', 'JSON file')], default='yaml', max_length=8)),
                ('pipeline', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='source_file_meta', to='pipelines.pipeline')),
                ('source_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta', to='pipelines.pipelinesourcefile')),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_pipeline_source_file_metas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('uploader',),
            },
        ),
        migrations.AddField(
            model_name='pipeline',
            name='plugins',
            field=models.ManyToManyField(related_name='pipelines', through='pipelines.PluginPiping', to='plugins.plugin'),
        ),
        migrations.CreateModel(
            name='DefaultPipingStrParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=600, null=True)),
                ('plugin_param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='string_piping_default', to='plugins.pluginparameter')),
                ('plugin_piping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='string_param', to='pipelines.pluginpiping')),
            ],
            options={
                'unique_together': {('plugin_piping', 'plugin_param')},
            },
        ),
        migrations.CreateModel(
            name='DefaultPipingIntParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(null=True)),
                ('plugin_param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integer_piping_default', to='plugins.pluginparameter')),
                ('plugin_piping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integer_param', to='pipelines.pluginpiping')),
            ],
            options={
                'unique_together': {('plugin_piping', 'plugin_param')},
            },
        ),
        migrations.CreateModel(
            name='DefaultPipingFloatParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(null=True)),
                ('plugin_param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='float_piping_default', to='plugins.pluginparameter')),
                ('plugin_piping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='float_param', to='pipelines.pluginpiping')),
            ],
            options={
                'unique_together': {('plugin_piping', 'plugin_param')},
            },
        ),
        migrations.CreateModel(
            name='DefaultPipingBoolParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField(null=True)),
                ('plugin_param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boolean_piping_default', to='plugins.pluginparameter')),
                ('plugin_piping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boolean_param', to='pipelines.pluginpiping')),
            ],
            options={
                'unique_together': {('plugin_piping', 'plugin_param')},
            },
        ),
    ]
