# Generated by Django 5.2.9 on 2026-04-28 19:24

import plugins.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluginpiping',
            name='cpu_limit',
            field=plugins.fields.CPUField(null=True),
        ),
        migrations.AddField(
            model_name='pluginpiping',
            name='gpu_limit',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pluginpiping',
            name='memory_limit',
            field=plugins.fields.MemoryField(null=True),
        ),
        migrations.AddField(
            model_name='pluginpiping',
            name='number_of_workers',
            field=models.IntegerField(null=True),
        ),
    ]
