# Generated by Django 2.1.4 on 2020-02-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0003_auto_20190524_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultpipingpathparameter',
            name='value',
            field=models.CharField(max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='defaultpipingstrparameter',
            name='value',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
