# Generated by Django 2.1.4 on 2020-02-13 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0004_auto_20200211_1602'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='defaultpipingpathparameter',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='defaultpipingpathparameter',
            name='plugin_param',
        ),
        migrations.RemoveField(
            model_name='defaultpipingpathparameter',
            name='plugin_piping',
        ),
        migrations.DeleteModel(
            name='DefaultPipingPathParameter',
        ),
    ]
