# Generated by Django 4.0 on 2022-09-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0006_alter_defaultpipingboolparameter_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluginpiping',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
