# Generated by Django 4.0 on 2022-10-19 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0007_pluginpiping_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pluginpiping',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='pluginpiping',
            unique_together={('title', 'pipeline')},
        ),
    ]
