# Generated by Django 4.0 on 2023-01-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0008_alter_pluginpiping_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultpipingstrparameter',
            name='value',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
