# Generated by Django 4.0 on 2023-05-17 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0010_pipelinesourcefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinesourcefile',
            name='type',
            field=models.CharField(blank=True, choices=[('yaml', 'YAML file'), ('json', 'JSON file')], default='yaml', max_length=8),
        ),
    ]
