# Generated by Django 4.2.5 on 2023-12-19 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_chrisfolder_chrislinkfile'),
        ('pipelines', '0011_pipelinesourcefile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinesourcefile',
            name='parent_folder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_source_files', to='core.chrisfolder'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pipelinesourcefile',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_pipeline_source_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pipelinesourcefile',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
