---
# Automate the deployment of ChRIS podman socket service and TCP service as a Podman container running as a Systemd service.

- name: Create the {{ PODMAN_TCP_NAME }} systemd service {{ PODMAN_TCP_SYSTEMD }}.
  template:
    src: chris_podman_tcp.service
    dest: "{{ PODMAN_TCP_SYSTEMD }}"
  become: true
  when: ansible_pkg_mgr != 'homebrew'

- name: Reload the services.
  systemd:
    daemon_reload: true
  become: true
  when: ansible_pkg_mgr != 'homebrew'

- name: Start and enable the podman.socket service.
  service:
    name: "podman.socket"
    enabled: true
    state: started
  become: true

- name: Start and enable the {{ PODMAN_TCP_SERVICE }} service.
  service:
    name: "{{ PODMAN_TCP_SERVICE }}"
    enabled: false
    state: restarted
  become: true
  when: ansible_pkg_mgr != 'homebrew'
