---
# Automate the deployment of ChRIS store as a Podman container running as a Systemd service. 
- name: Create the {{ STORE_NAME }} systemd service {{ STORE_SYSTEMD }}. 
  template:
    src: chris_store.service
    dest: "{{ STORE_SYSTEMD }}"
  become: true
  when: ansible_pkg_mgr != 'homebrew'
- name: Reload the services. 
  systemd:
    daemon_reload: true
  become: true
  when: ansible_pkg_mgr != 'homebrew'
- name: Start and enable the {{ STORE_SERVICE }} service. 
  service:
    name: "{{ STORE_SERVICE }}"
    enabled: true
    state: restarted
  become: true
  when: ansible_pkg_mgr != 'homebrew'
