---
# Automate the deployment of ChRIS worker periodic as a Podman container running as a Systemd service. 
- name: Create the {{ WORKER_PERIODIC_NAME }} systemd service {{ WORKER_PERIODIC_SYSTEMD }}. 
  template:
    src: chris_worker_periodic.service
    dest: "{{ WORKER_PERIODIC_SYSTEMD }}"
  become: true
  when: ansible_pkg_mgr != 'homebrew'
- name: Reload the services. 
  systemd:
    daemon_reload: true
  become: true
  when: ansible_pkg_mgr != 'homebrew'
- name: Start and enable the {{ WORKER_PERIODIC_SERVICE }} service. 
  service:
    name: "{{ WORKER_PERIODIC_SERVICE }}"
    enabled: true
    state: restarted
  become: true
  when: ansible_pkg_mgr != 'homebrew'
