---
- name: Install the ChRIS containers locally in podman with Ansible
  connection: local
  hosts: localhost

  roles:
    # Run the chris_defaults role to load the ChRIS related variables. 
    - chris_defaults
    # Now run the chris_scheduler role to install the scheduler container to podman. 
    - chris_scheduler
