---
# define the playbook to run locally
- name: Install the ChRIS containers locally in podman with Ansible
  connection: local
  hosts: localhost


  # Run the chris_defaults role to load the ChRIS related variables.
  roles:
    - chris_defaults
    # Now run the chris_worker_periodic role to install the worker_periodic container to podman.
    - chris_worker_periodic
