# Generated by Django 4.2.5 on 2024-04-11 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PACS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=20, unique=True)),
                ('folder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pacs', to='core.chrisfolder')),
            ],
        ),
        migrations.CreateModel(
            name='PACSFile',
            fields=[
            ],
            options={
                'ordering': ('-fname',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.chrisfile',),
        ),
        migrations.CreateModel(
            name='PACSSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('PatientID', models.CharField(db_index=True, max_length=100)),
                ('PatientName', models.CharField(blank=True, max_length=150)),
                ('PatientBirthDate', models.DateField(blank=True, null=True)),
                ('PatientAge', models.IntegerField(blank=True, null=True)),
                ('PatientSex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('StudyDate', models.DateField(db_index=True)),
                ('AccessionNumber', models.CharField(blank=True, db_index=True, max_length=100)),
                ('Modality', models.CharField(blank=True, max_length=15)),
                ('ProtocolName', models.CharField(blank=True, max_length=64)),
                ('StudyInstanceUID', models.CharField(max_length=100)),
                ('StudyDescription', models.CharField(blank=True, max_length=400)),
                ('SeriesInstanceUID', models.CharField(db_index=True, max_length=100)),
                ('SeriesDescription', models.CharField(blank=True, max_length=400)),
                ('folder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pacs_series', to='core.chrisfolder')),
                ('pacs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_list', to='pacsfiles.pacs')),
            ],
            options={
                'ordering': ('pacs', 'PatientID'),
                'unique_together': {('pacs', 'SeriesInstanceUID')},
            },
        ),
    ]
