# Generated by Django 2.1.4 on 2020-02-15 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PACSFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('fname', models.FileField(blank=True, max_length=500, upload_to='')),
                ('mrn', models.CharField(blank=True, max_length=10)),
                ('patient_name', models.CharField(blank=True, max_length=15)),
                ('study', models.CharField(blank=True, max_length=150)),
                ('series', models.CharField(blank=True, max_length=150)),
                ('name', models.CharField(blank=True, max_length=175)),
            ],
            options={
                'ordering': ('-fname',),
            },
        ),
    ]
