# Generated by Django 2.1.4 on 2020-04-22 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PACS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PACSFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('fname', models.FileField(max_length=600, upload_to='')),
                ('PatientID', models.CharField(max_length=15)),
                ('PatientName', models.CharField(max_length=30)),
                ('StudyInstanceUID', models.CharField(max_length=50)),
                ('StudyDescription', models.CharField(blank=True, max_length=200)),
                ('SeriesInstanceUID', models.CharField(max_length=50)),
                ('SeriesDescription', models.CharField(blank=True, max_length=200)),
                ('name', models.CharField(max_length=175)),
                ('pacs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacsfiles.PACS')),
            ],
            options={
                'ordering': ('-fname',),
            },
        ),
    ]
