# Generated by Django 2.1.4 on 2020-04-20 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacsfiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PACS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='pacsfile',
            name='fname',
            field=models.FileField(max_length=500, upload_to=''),
        ),
        migrations.AlterField(
            model_name='pacsfile',
            name='mrn',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pacsfile',
            name='name',
            field=models.CharField(max_length=175),
        ),
        migrations.AlterField(
            model_name='pacsfile',
            name='patient_name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='pacsfile',
            name='series',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='pacsfile',
            name='study',
            field=models.CharField(max_length=150),
        ),
        migrations.AddField(
            model_name='pacsfile',
            name='pacs',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pacsfiles.PACS'),
            preserve_default=False,
        ),
    ]
