# Generated by Django 4.2.5 on 2024-10-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacsfiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacs',
            name='active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
