# Generated by Django 4.2.5 on 2024-11-05 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pacsfiles', '0002_pacs_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='PACSQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(db_index=True, max_length=300)),
                ('query', models.JSONField()),
                ('description', models.CharField(blank=True, max_length=700)),
                ('result', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pacs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_list', to='pacsfiles.pacs')),
            ],
            options={
                'ordering': ('pacs', 'owner', '-creation_date'),
                'unique_together': {('pacs', 'owner', 'title')},
            },
        ),
    ]
