# Generated by Django 2.2.12 on 2020-07-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacsfiles', '0002_auto_20200616_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacsfile',
            name='Modality',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
