# Generated by Django 4.2.5 on 2024-11-27 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pacsfiles', '0003_pacsquery'),
    ]

    operations = [
        migrations.CreateModel(
            name='PACSRetrieve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('result', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pacs_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retrieve_list', to='pacsfiles.pacsquery')),
            ],
            options={
                'ordering': ('pacs_query', '-creation_date'),
            },
        ),
    ]
