# Generated by Django 4.2.5 on 2024-12-07 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacsfiles', '0004_pacsretrieve'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacsquery',
            name='status',
            field=models.CharField(choices=[('created', 'Default initial'), ('sent', 'Sent to PACS'), ('succeeded', 'Finished successfully'), ('errored', 'Finished with error')], default='created', max_length=10),
        ),
        migrations.AddField(
            model_name='pacsretrieve',
            name='status',
            field=models.CharField(choices=[('created', 'Default initial'), ('sent', 'Sent to PACS'), ('succeeded', 'Finished successfully'), ('errored', 'Finished with error')], default='created', max_length=10),
        ),
    ]
