# Generated by Django 2.2.24 on 2021-08-31 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacsfiles', '0004_auto_20210409_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacsfile',
            name='AccessionNumber',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pacsfile',
            name='PatientID',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pacsfile',
            name='SeriesDescription',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='pacsfile',
            name='SeriesInstanceUID',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pacsfile',
            name='StudyDescription',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='pacsfile',
            name='StudyInstanceUID',
            field=models.CharField(max_length=100),
        ),
    ]
