# Generated by Django 5.1.7 on 2025-04-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacsfiles', '0005_pacsquery_status_pacsretrieve_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacs',
            name='identifier',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
