# Generated by Django 5.2.9 on 2025-12-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacsfiles', '0006_alter_pacs_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacsquery',
            name='execute',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
