# Generated by Django 4.2.5 on 2023-12-19 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_chrisfolder_chrislinkfile'),
        ('pacsfiles', '0007_alter_pacsfile_patientsex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacsfile',
            name='pacs',
        ),
        migrations.AddField(
            model_name='pacs',
            name='folder',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pacs', to='core.chrisfolder'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pacsfile',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pacsfile',
            name='parent_folder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pacs_files', to='core.chrisfolder'),
            preserve_default=False,
        ),
    ]
