# Generated by Django 5.2.1 on 2026-01-06 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacsfiles', '0007_pacsquery_execute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacsseries',
            name='PatientAge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
