# Generated by Django 5.2.9 on 2026-05-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_chrisfolder_deletion_error_and_more'),
        ('pacsfiles', '0008_pacsseries_deletion_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacsseries',
            name='BodyPartExamined',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='pacsseries',
            name='Manufacturer',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='pacsseries',
            name='PerformedProcedureStepStartDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pacsseries',
            name='PerformedProcedureStepStartTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pacsseries',
            name='SeriesNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pacsseries',
            name='StudyTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pacsseries',
            name='Modality',
            field=models.CharField(blank=True, db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='pacsseries',
            name='StudyInstanceUID',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='pacsseries',
            index=models.Index(fields=['pacs', 'StudyInstanceUID'], name='pacsseries_pacs_study_idx'),
        ),
    ]
