# Generated by Django 5.2.9 on 2026-07-01 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicomweb', '0003_pacsstudy'),
        ('pacsfiles', '0009_pacsseries_qido_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacsseries',
            name='study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series', to='dicomweb.pacsstudy'),
        ),
    ]
