# Generated by Django 2.1.4 on 2019-02-21 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pipelines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=800)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='pipelines.Pipeline')),
            ],
            options={
                'ordering': ('pipeline',),
            },
        ),
    ]
