# Generated by Django 4.0 on 2022-09-10 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelineinstances', '0003_auto_20190719_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelineinstance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
