# Generated by Django 5.2.9 on 2026-05-01 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
