# Generated by Django 4.2.5 on 2024-04-10 04:26

from django.db import migrations, models
import django.db.models.deletion
import plugins.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComputeResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('compute_url', models.URLField(max_length=300)),
                ('compute_auth_url', models.URLField(blank=True, max_length=350)),
                ('compute_innetwork', models.BooleanField(blank=True, default=False)),
                ('compute_user', models.CharField(max_length=32)),
                ('compute_password', models.CharField(max_length=100)),
                ('compute_auth_token', models.CharField(blank=True, default='initial_token', max_length=500)),
                ('description', models.CharField(blank=True, max_length=600)),
                ('max_job_exec_seconds', models.IntegerField(blank=True, default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('version', models.CharField(max_length=10)),
                ('dock_image', models.CharField(max_length=500)),
                ('execshell', models.CharField(max_length=50)),
                ('selfpath', models.CharField(max_length=512)),
                ('selfexec', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=2000)),
                ('min_gpu_limit', models.IntegerField(blank=True, default=0, null=True)),
                ('max_gpu_limit', models.IntegerField(blank=True, default=0, null=True)),
                ('min_number_of_workers', models.IntegerField(blank=True, default=1, null=True)),
                ('max_number_of_workers', models.IntegerField(blank=True, default=2147483647, null=True)),
                ('min_cpu_limit', plugins.fields.CPUField(blank=True, default=1000, null=True)),
                ('max_cpu_limit', plugins.fields.CPUField(blank=True, default=2147483647, null=True)),
                ('min_memory_limit', plugins.fields.MemoryField(blank=True, default=200, null=True)),
                ('max_memory_limit', plugins.fields.MemoryField(blank=True, default=2147483647, null=True)),
                ('compute_resources', models.ManyToManyField(related_name='plugins', to='plugins.computeresource')),
            ],
            options={
                'ordering': ('meta', '-creation_date'),
            },
        ),
        migrations.CreateModel(
            name='PluginMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(blank=True, max_length=400)),
                ('stars', models.IntegerField(default=0)),
                ('public_repo', models.URLField(blank=True, max_length=300)),
                ('license', models.CharField(blank=True, max_length=50)),
                ('type', models.CharField(choices=[('ds', 'Data synthesis'), ('fs', 'Feed synthesis'), ('ts', 'Topology synthesis')], default='ds', max_length=4)),
                ('icon', models.URLField(blank=True, max_length=300)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('authors', models.CharField(blank=True, max_length=200)),
                ('documentation', models.CharField(blank=True, max_length=800)),
            ],
            options={
                'ordering': ('type', '-creation_date'),
            },
        ),
        migrations.CreateModel(
            name='PluginParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('flag', models.CharField(max_length=52)),
                ('short_flag', models.CharField(blank=True, max_length=52)),
                ('action', models.CharField(default='store', max_length=20)),
                ('optional', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('string', 'String values'), ('float', 'Float values'), ('boolean', 'Boolean values'), ('integer', 'Integer values'), ('path', 'Path values'), ('unextpath', 'Unextracted path values')], default='string', max_length=10)),
                ('help', models.TextField(blank=True)),
                ('ui_exposed', models.BooleanField(default=True)),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='plugins.plugin')),
            ],
            options={
                'ordering': ('plugin',),
            },
        ),
        migrations.AddField(
            model_name='plugin',
            name='meta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plugins', to='plugins.pluginmeta'),
        ),
        migrations.CreateModel(
            name='DefaultStrParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=600)),
                ('plugin_param', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='string_default', to='plugins.pluginparameter')),
            ],
        ),
        migrations.CreateModel(
            name='DefaultIntParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('plugin_param', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='integer_default', to='plugins.pluginparameter')),
            ],
        ),
        migrations.CreateModel(
            name='DefaultFloatParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('plugin_param', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='float_default', to='plugins.pluginparameter')),
            ],
        ),
        migrations.CreateModel(
            name='DefaultBoolParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField()),
                ('plugin_param', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boolean_default', to='plugins.pluginparameter')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='plugin',
            unique_together={('meta', 'version'), ('meta', 'dock_image')},
        ),
    ]
