# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-06 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoolParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='IntParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PluginInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(auto_now_add=True)),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plugin_inst', to='plugins.Plugin')),
            ],
            options={
                'ordering': ('start_date',),
            },
        ),
        migrations.CreateModel(
            name='PluginParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('optional', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('string', 'String values'), ('double', 'Float values'), ('boolean', 'Boolean values'), ('integer', 'Integer values')], default='string', max_length=10)),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter', to='plugins.Plugin')),
            ],
            options={
                'ordering': ('start_date',),
            },
        ),
        migrations.CreateModel(
            name='StringParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
                ('plugin_inst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='string_param', to='plugins.PluginInstance')),
                ('plugin_param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='string_inst', to='plugins.PluginInstance')),
            ],
        ),
        migrations.AddField(
            model_name='intparameter',
            name='plugin_inst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='int_param', to='plugins.PluginInstance'),
        ),
        migrations.AddField(
            model_name='intparameter',
            name='plugin_param',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='int_inst', to='plugins.PluginInstance'),
        ),
        migrations.AddField(
            model_name='boolparameter',
            name='plugin_inst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bool_param', to='plugins.PluginInstance'),
        ),
        migrations.AddField(
            model_name='boolparameter',
            name='plugin_param',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bool_inst', to='plugins.PluginInstance'),
        ),
    ]
