# Generated by Django 5.2.1 on 2025-10-16 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plugin',
            options={'ordering': ('meta', '-version')},
        ),
    ]
