# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-07 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0002_auto_20160706_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloatParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('plugin_inst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='float_param', to='plugins.PluginInstance')),
                ('plugin_param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='float_inst', to='plugins.PluginInstance')),
            ],
        ),
        migrations.AlterField(
            model_name='pluginparameter',
            name='type',
            field=models.CharField(choices=[('string', 'String values'), ('float', 'Float values'), ('boolean', 'Boolean values'), ('integer', 'Integer values')], default='string', max_length=10),
        ),
    ]
