# Generated by Django 5.2.9 on 2026-03-16 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0002_alter_plugin_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='computeresource',
            name='compute_requires_copy_job',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='computeresource',
            name='compute_requires_upload_job',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='computeresource',
            name='compute_innetwork',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
