# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-08 19:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plugins', '0003_auto_20160707_1057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pluginparameter',
            options={'ordering': ('plugin',)},
        ),
        migrations.RemoveField(
            model_name='pluginparameter',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='pluginparameter',
            name='start_date',
        ),
        migrations.AddField(
            model_name='plugininstance',
            name='owner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
