# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-12 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0004_auto_20160708_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugininstance',
            name='plugin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='plugins.Plugin'),
        ),
        migrations.AlterField(
            model_name='pluginparameter',
            name='optional',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pluginparameter',
            name='plugin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='plugins.Plugin'),
        ),
    ]
