# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-13 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0005_auto_20160712_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boolparameter',
            name='plugin_param',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bool_inst', to='plugins.PluginParameter'),
        ),
        migrations.AlterField(
            model_name='floatparameter',
            name='plugin_param',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='float_inst', to='plugins.PluginParameter'),
        ),
        migrations.AlterField(
            model_name='intparameter',
            name='plugin_param',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='int_inst', to='plugins.PluginParameter'),
        ),
        migrations.AlterField(
            model_name='stringparameter',
            name='plugin_param',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='string_inst', to='plugins.PluginParameter'),
        ),
    ]
