# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-25 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0006_auto_20160713_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugin',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
