# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-02 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0007_auto_20160725_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugininstance',
            name='previous',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='plugins.PluginInstance'),
            preserve_default=False,
        ),
    ]
