# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-08 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0009_auto_20160802_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugininstance',
            name='previous',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next', to='plugins.PluginInstance'),
        ),
    ]
