# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-29 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0010_auto_20160808_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugin',
            name='type',
            field=models.CharField(choices=[('ds', 'Data plugin'), ('fs', 'Filesystem plugin')], default='ds', max_length=4),
        ),
    ]
