# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-07 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0011_auto_20160829_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugininstance',
            name='status',
            field=models.CharField(default='finished', max_length=30),
            preserve_default=False,
        ),
    ]
