# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-21 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0013_auto_20160907_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluginparameter',
            name='default',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pluginparameter',
            name='help',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='stringparameter',
            name='value',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
