# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-22 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0014_auto_20160921_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='dock_image',
            field=models.CharField(default='fnndsc/pl-simplefsapp', max_length=500),
            preserve_default=False,
        ),
    ]
