# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-10-18 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0015_plugin_dock_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=200)),
                ('plugin_inst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_param', to='plugins.PluginInstance')),
            ],
        ),
        migrations.AlterField(
            model_name='pluginparameter',
            name='type',
            field=models.CharField(choices=[('string', 'String values'), ('float', 'Float values'), ('boolean', 'Boolean values'), ('integer', 'Integer values'), ('path', 'Path values')], default='string', max_length=10),
        ),
        migrations.AddField(
            model_name='pathparameter',
            name='plugin_param',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_inst', to='plugins.PluginParameter'),
        ),
    ]
