# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-03-20 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0017_auto_20180125_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='max_gpu_limit',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='plugin',
            name='min_gpu_limit',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='plugininstance',
            name='gpu_limit',
            field=models.IntegerField(null=True),
        ),
    ]
