# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-27 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0017_auto_20180125_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputeResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compute_resource_identifier', models.CharField(max_length=100)),
            ],
        ),
        migrations.RunSQL("INSERT INTO plugins_computeresource (compute_resource_identifier) VALUES ('host');"),
        migrations.RunSQL("INSERT INTO plugins_computeresource (compute_resource_identifier) VALUES ('localhost');"),
        migrations.RunSQL("INSERT INTO plugins_computeresource (compute_resource_identifier) VALUES ('moc');"),
        migrations.RunSQL("INSERT INTO plugins_computeresource (compute_resource_identifier) VALUES ('openshiftlocal');"),
    ]
