# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-04-02 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import plugins.models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0018_auto_20180320_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='max_cpu_limit',
            field=plugins.models.CPUField(default=2147483647, null=True),
        ),
        migrations.AddField(
            model_name='plugin',
            name='max_memory_limit',
            field=plugins.models.MemoryField(default=2147483647, null=True),
        ),
        migrations.AddField(
            model_name='plugin',
            name='max_number_of_workers',
            field=models.IntegerField(default=2147483647, null=True),
        ),
        migrations.AddField(
            model_name='plugin',
            name='min_cpu_limit',
            field=plugins.models.CPUField(default=1000, null=True),
        ),
        migrations.AddField(
            model_name='plugin',
            name='min_memory_limit',
            field=plugins.models.MemoryField(default=200, null=True),
        ),
        migrations.AddField(
            model_name='plugin',
            name='min_number_of_workers',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='plugininstance',
            name='cpu_limit',
            field=plugins.models.CPUField(null=True),
        ),
        migrations.AddField(
            model_name='plugininstance',
            name='memory_limit',
            field=plugins.models.MemoryField(null=True),
        ),
        migrations.AddField(
            model_name='plugininstance',
            name='number_of_workers',
            field=models.IntegerField(null=True),
        ),
    ]
