# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-03-15 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0019_plugin_compute_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugininstance',
            name='compute_resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plugin_instance', to='plugins.ComputeResource'),
        ),
    ]
