# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-05-02 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0019_auto_20180430_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugin',
            name='max_gpu_limit',
            field=models.IntegerField(default=2147483647, null=True),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='min_gpu_limit',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
