# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-05-03 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0020_auto_20180502_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluginparameter',
            name='flag',
            field=models.CharField(default='', max_length=52),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pluginparameter',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
