# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-04-11 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0019_auto_20180402_1102'),
        ('plugins', '0020_plugininstance_compute_resource'),
    ]

    operations = [
    ]
