# Generated by Django 2.0.7 on 2018-10-10 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0021_auto_20180504_1608'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plugininstance',
            options={'ordering': ('-start_date',)},
        ),
        migrations.AlterField(
            model_name='boolparameter',
            name='plugin_inst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boolean_param', to='plugins.PluginInstance'),
        ),
        migrations.AlterField(
            model_name='boolparameter',
            name='plugin_param',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boolean_inst', to='plugins.PluginParameter'),
        ),
        migrations.AlterField(
            model_name='intparameter',
            name='plugin_inst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integer_param', to='plugins.PluginInstance'),
        ),
        migrations.AlterField(
            model_name='intparameter',
            name='plugin_param',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integer_inst', to='plugins.PluginParameter'),
        ),
    ]
