# Generated by Django 2.1.4 on 2019-01-14 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0008_auto_20190114_1437'),
        ('plugins', '0022_auto_20181010_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='PluginInstanceFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('fname', models.FileField(max_length=2048, upload_to='')),
            ],
            options={
                'ordering': ('fname',),
            },
        ),
        migrations.AddField(
            model_name='plugininstance',
            name='feed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='plugin_instances', to='feeds.Feed'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plugininstance',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='boolparameter',
            name='value',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='plugininstancefile',
            name='plugin_inst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='plugins.PluginInstance'),
        ),
    ]
