# Generated by Django 2.1.4 on 2019-01-16 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0023_auto_20190114_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boolparameter',
            name='plugin_inst',
        ),
        migrations.RemoveField(
            model_name='boolparameter',
            name='plugin_param',
        ),
        migrations.RemoveField(
            model_name='floatparameter',
            name='plugin_inst',
        ),
        migrations.RemoveField(
            model_name='floatparameter',
            name='plugin_param',
        ),
        migrations.RemoveField(
            model_name='intparameter',
            name='plugin_inst',
        ),
        migrations.RemoveField(
            model_name='intparameter',
            name='plugin_param',
        ),
        migrations.RemoveField(
            model_name='pathparameter',
            name='plugin_inst',
        ),
        migrations.RemoveField(
            model_name='pathparameter',
            name='plugin_param',
        ),
        migrations.RemoveField(
            model_name='plugininstance',
            name='compute_resource',
        ),
        migrations.RemoveField(
            model_name='plugininstance',
            name='feed',
        ),
        migrations.RemoveField(
            model_name='plugininstance',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='plugininstance',
            name='plugin',
        ),
        migrations.RemoveField(
            model_name='plugininstance',
            name='previous',
        ),
        migrations.RemoveField(
            model_name='plugininstancefile',
            name='plugin_inst',
        ),
        migrations.RemoveField(
            model_name='stringparameter',
            name='plugin_inst',
        ),
        migrations.RemoveField(
            model_name='stringparameter',
            name='plugin_param',
        ),
        migrations.DeleteModel(
            name='BoolParameter',
        ),
        migrations.DeleteModel(
            name='FloatParameter',
        ),
        migrations.DeleteModel(
            name='IntParameter',
        ),
        migrations.DeleteModel(
            name='PathParameter',
        ),
        migrations.DeleteModel(
            name='PluginInstance',
        ),
        migrations.DeleteModel(
            name='PluginInstanceFile',
        ),
        migrations.DeleteModel(
            name='StringParameter',
        ),
    ]
