# Generated by Django 2.1.4 on 2019-01-28 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0025_auto_20190122_1745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pluginpiping',
            options={'ordering': ('pipeline',)},
        ),
        migrations.AddField(
            model_name='pluginpiping',
            name='previous',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next', to='plugins.PluginPiping'),
        ),
        migrations.AlterUniqueTogether(
            name='pluginpiping',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='pluginpiping',
            name='position',
        ),
    ]
