# Generated by Django 2.1.4 on 2019-02-11 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0026_auto_20190128_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultBoolParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='DefaultFloatParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DefaultIntParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DefaultPathParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DefaultPipingBoolParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DefaultPipingFloatParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='DefaultPipingIntParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(blank=True, default=1)),
            ],
        ),
        migrations.CreateModel(
            name='DefaultPipingPathParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DefaultPipingStringParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DefaultStringParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='pluginparameter',
            name='default',
        ),
        migrations.AddField(
            model_name='pipeline',
            name='locked',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pluginpiping',
            name='pipeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plugin_pipings', to='plugins.Pipeline'),
        ),
        migrations.AddField(
            model_name='defaultstringparameter',
            name='plugin_param',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='string_default', to='plugins.PluginParameter'),
        ),
        migrations.AddField(
            model_name='defaultpipingstringparameter',
            name='plugin_param',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='string_piping_default', to='plugins.PluginParameter'),
        ),
        migrations.AddField(
            model_name='defaultpipingstringparameter',
            name='plugin_piping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='string_param', to='plugins.PluginPiping'),
        ),
        migrations.AddField(
            model_name='defaultpipingpathparameter',
            name='plugin_param',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_piping_default', to='plugins.PluginParameter'),
        ),
        migrations.AddField(
            model_name='defaultpipingpathparameter',
            name='plugin_piping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_param', to='plugins.PluginPiping'),
        ),
        migrations.AddField(
            model_name='defaultpipingintparameter',
            name='plugin_param',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integer_piping_default', to='plugins.PluginParameter'),
        ),
        migrations.AddField(
            model_name='defaultpipingintparameter',
            name='plugin_piping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integer_param', to='plugins.PluginPiping'),
        ),
        migrations.AddField(
            model_name='defaultpipingfloatparameter',
            name='plugin_param',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='float_piping_default', to='plugins.PluginParameter'),
        ),
        migrations.AddField(
            model_name='defaultpipingfloatparameter',
            name='plugin_piping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='float_param', to='plugins.PluginPiping'),
        ),
        migrations.AddField(
            model_name='defaultpipingboolparameter',
            name='plugin_param',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boolean_piping_default', to='plugins.PluginParameter'),
        ),
        migrations.AddField(
            model_name='defaultpipingboolparameter',
            name='plugin_piping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boolean_param', to='plugins.PluginPiping'),
        ),
        migrations.AddField(
            model_name='defaultpathparameter',
            name='plugin_param',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='path_default', to='plugins.PluginParameter'),
        ),
        migrations.AddField(
            model_name='defaultintparameter',
            name='plugin_param',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='integer_default', to='plugins.PluginParameter'),
        ),
        migrations.AddField(
            model_name='defaultfloatparameter',
            name='plugin_param',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='float_default', to='plugins.PluginParameter'),
        ),
        migrations.AddField(
            model_name='defaultboolparameter',
            name='plugin_param',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boolean_default', to='plugins.PluginParameter'),
        ),
    ]
