# Generated by Django 2.1.4 on 2019-02-07 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0026_auto_20190128_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultBoolParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField(blank=True, default=False)),
                ('plugin_param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boolean_default', to='plugins.PluginParameter')),
            ],
        ),
        migrations.CreateModel(
            name='DefaultFloatParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('plugin_param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='float_default', to='plugins.PluginParameter')),
            ],
        ),
        migrations.CreateModel(
            name='DefaultIntParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('plugin_param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integer_default', to='plugins.PluginParameter')),
            ],
        ),
        migrations.CreateModel(
            name='DefaultPathParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=200)),
                ('plugin_param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_default', to='plugins.PluginParameter')),
            ],
        ),
        migrations.CreateModel(
            name='DefaultStringParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=200)),
                ('plugin_param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='string_default', to='plugins.PluginParameter')),
            ],
        ),
        migrations.AddField(
            model_name='pipeline',
            name='locked',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pluginpiping',
            name='pipeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plugin_tree', to='plugins.Pipeline'),
        ),
        migrations.AddField(
            model_name='defaultstringparameter',
            name='plugin_piping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='string_param', to='plugins.PluginPiping'),
        ),
        migrations.AddField(
            model_name='defaultpathparameter',
            name='plugin_piping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_param', to='plugins.PluginPiping'),
        ),
        migrations.AddField(
            model_name='defaultintparameter',
            name='plugin_piping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integer_param', to='plugins.PluginPiping'),
        ),
        migrations.AddField(
            model_name='defaultfloatparameter',
            name='plugin_piping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='float_param', to='plugins.PluginPiping'),
        ),
        migrations.AddField(
            model_name='defaultboolparameter',
            name='plugin_piping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boolean_param', to='plugins.PluginPiping'),
        ),
    ]
