# Generated by Django 2.1.4 on 2019-02-21 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plugininstances', '0005_auto_20190221_1803'),
        ('plugins', '0027_auto_20190212_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaultpipingboolparameter',
            name='plugin_param',
        ),
        migrations.RemoveField(
            model_name='defaultpipingboolparameter',
            name='plugin_piping',
        ),
        migrations.RemoveField(
            model_name='defaultpipingfloatparameter',
            name='plugin_param',
        ),
        migrations.RemoveField(
            model_name='defaultpipingfloatparameter',
            name='plugin_piping',
        ),
        migrations.RemoveField(
            model_name='defaultpipingintparameter',
            name='plugin_param',
        ),
        migrations.RemoveField(
            model_name='defaultpipingintparameter',
            name='plugin_piping',
        ),
        migrations.RemoveField(
            model_name='defaultpipingpathparameter',
            name='plugin_param',
        ),
        migrations.RemoveField(
            model_name='defaultpipingpathparameter',
            name='plugin_piping',
        ),
        migrations.RemoveField(
            model_name='defaultpipingstrparameter',
            name='plugin_param',
        ),
        migrations.RemoveField(
            model_name='defaultpipingstrparameter',
            name='plugin_piping',
        ),
        migrations.RemoveField(
            model_name='pipeline',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='pipeline',
            name='plugins',
        ),
        migrations.RemoveField(
            model_name='pluginpiping',
            name='pipeline',
        ),
        migrations.RemoveField(
            model_name='pluginpiping',
            name='plugin',
        ),
        migrations.RemoveField(
            model_name='pluginpiping',
            name='previous',
        ),
        migrations.DeleteModel(
            name='DefaultPipingBoolParameter',
        ),
        migrations.DeleteModel(
            name='DefaultPipingFloatParameter',
        ),
        migrations.DeleteModel(
            name='DefaultPipingIntParameter',
        ),
        migrations.DeleteModel(
            name='DefaultPipingPathParameter',
        ),
        migrations.DeleteModel(
            name='DefaultPipingStrParameter',
        ),
        migrations.DeleteModel(
            name='Pipeline',
        ),
        migrations.DeleteModel(
            name='PluginPiping',
        ),
    ]
