# Generated by Django 2.1.4 on 2019-04-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0028_auto_20190221_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugin',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='plugin',
            unique_together={('name', 'version')},
        ),
    ]
