# Generated by Django 2.1.4 on 2020-03-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0032_auto_20200213_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluginparameter',
            name='short_flag',
            field=models.CharField(blank=True, max_length=52),
        ),
    ]
