# Generated by Django 2.1.4 on 2020-04-20 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0033_pluginparameter_short_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computeresource',
            name='compute_resource_identifier',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
