# Generated by Django 2.2.12 on 2020-05-15 03:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0034_auto_20200420_2320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computeresource',
            old_name='compute_resource_identifier',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='plugin',
            name='compute_resource',
        ),
        migrations.AddField(
            model_name='computeresource',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='computeresource',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='computeresource',
            name='modification_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plugin',
            name='compute_resources',
            field=models.ManyToManyField(related_name='plugins', to='plugins.ComputeResource'),
        ),
    ]
