# Generated by Django 2.2.12 on 2020-05-15 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0035_auto_20200514_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='icon',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
