# Generated by Django 2.2.12 on 2020-05-18 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0036_plugin_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugin',
            name='type',
            field=models.CharField(choices=[('ds', 'Data synthesis'), ('fs', 'Feed synthesis')], default='ds', max_length=4),
        ),
    ]
