# Generated by Django 2.2.12 on 2020-06-10 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0037_auto_20200518_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugin',
            name='max_gpu_limit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
