# Generated by Django 2.2.12 on 2020-06-11 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0038_auto_20200610_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='PluginMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('stars', models.IntegerField(default=0)),
                ('public_repo', models.URLField(blank=True, max_length=300)),
                ('license', models.CharField(blank=True, max_length=50)),
                ('type', models.CharField(choices=[('ds', 'Data synthesis'), ('fs', 'Feed synthesis')], default='ds', max_length=4)),
                ('icon', models.URLField(blank=True, max_length=300)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('authors', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ('type', '-creation_date'),
            },
        ),
        migrations.AlterModelOptions(
            name='plugin',
            options={'ordering': ('meta', '-creation_date')},
        ),
        migrations.AlterField(
            model_name='plugin',
            name='description',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='title',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='plugin',
            name='meta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='plugins', to='plugins.PluginMeta'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='plugin',
            unique_together={('meta', 'version')},
        ),
        migrations.RemoveField(
            model_name='plugin',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='plugin',
            name='category',
        ),
        migrations.RemoveField(
            model_name='plugin',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='plugin',
            name='license',
        ),
        migrations.RemoveField(
            model_name='plugin',
            name='modification_date',
        ),
        migrations.RemoveField(
            model_name='plugin',
            name='name',
        ),
        migrations.RemoveField(
            model_name='plugin',
            name='type',
        ),
    ]
