# Generated by Django 2.2.12 on 2020-08-18 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0040_auto_20200811_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='computeresource',
            name='compute_url',
            field=models.URLField(default='http://pfcon.remote:5005/api/v1/', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='computeresource',
            name='description',
            field=models.CharField(blank=True, max_length=600),
        ),
    ]
