# Generated by Django 2.2.12 on 2021-01-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0043_auto_20201208_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pluginmeta',
            name='type',
            field=models.CharField(choices=[('ds', 'Data synthesis'), ('fs', 'Feed synthesis'), ('ts', 'Topology synthesis')], default='ds', max_length=4),
        ),
    ]
