# Generated by Django 2.2.24 on 2022-08-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0046_auto_20220122_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computeresource',
            name='max_job_exec_seconds',
            field=models.IntegerField(blank=True, default=-1),
        ),
    ]
