# Generated by Django 4.0 on 2023-07-26 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0048_alter_computeresource_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='computeresource',
            name='compute_innetwork',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
