name: lint

on:
  - pull_request
  - push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install pre-commit
        run: |
          pip install pre-commit
      - name: Run pre-commit
        run: |
          pre-commit run --color=always --show-diff-on-failure --all-files
