# -*- coding: utf-8 -*-
"""
Django settings for chris_backend project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

from environs import Env

from __version__ import __version__
from plugins.enums import PLUGIN_TYPE_CHOICES, TYPE_CHOICES

# Environment variables-based secrets
env = Env()
env.read_env()  # also read .env file, if it exists


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Application definition
INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_filters',
    'django_celery_beat',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'collectionjson',
    'drf_spectacular',
    'core',
    'feeds',
    'plugins',
    'plugininstances',
    'pipelines',
    'userfiles',
    'pacsfiles',
    'filebrowser',
    'users',
    'workflows'
]

# Pagination
REST_FRAMEWORK = {
    'PAGE_SIZE': 10,
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'DEFAULT_RENDERER_CLASSES': (
        'collectionjson.renderers.CollectionJsonRenderer',
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ),
    'DEFAULT_PARSER_CLASSES': (
        'collectionjson.parsers.CollectionJsonParser',
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema'
}

MIDDLEWARE = [
    'core.middleware.ResponseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

ASGI_APPLICATION = 'config.asgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/New_York'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'

# https://whitenoise.readthedocs.io/en/stable/django.html
STORAGES = {
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# `./manage.py collectstatic` is run during build
STATIC_ROOT = '/opt/app-root/var/staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# drf-spectacular OPENAPI SCHEMA SETTINGS
SPECTACULAR_SETTINGS = {
    'TITLE': 'ChRIS Research Integration System: Ultron BackEnd (CUBE) API',
    'DESCRIPTION': (
        'The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. '
        'It manages ChRIS users, plugins, pipelines, and the provenance of '
        'data analyses as ChRIS feeds.'
    ),
    'VERSION': __version__,
    'LICENSE': {
        'name': 'MIT',
        'url': 'https://github.com/FNNDSC/ChRIS_ultron_backEnd/blob/master/LICENSE'
    },
    'EXTERNAL_DOCS': {
        'url': 'https://chrisproject.org/docs'
    },
    'CONTACT': {
        'name': 'Fetal-Neonatal Neuroimaging Developmental Science Center',
        'url': 'https://chrisproject.org',
        'email': 'dev@babymri.org'
    },
    'SERVE_INCLUDE_SCHEMA': True,
    'ENUM_NAME_OVERRIDES': {
        'PluginType': PLUGIN_TYPE_CHOICES,
        'PluginParameterType': TYPE_CHOICES,
    },
    'COMPONENT_SPLIT_REQUEST': env.bool("SPECTACULAR_SPLIT_REQUEST", False),
    'PREPROCESSING_HOOKS': [
        'drf_spectacular.hooks.preprocess_exclude_path_format',
    ],
    'POSTPROCESSING_HOOKS': [
        'drf_spectacular.hooks.postprocess_schema_enums',
        'collectionjson.spectacular_hooks.postprocess_remove_collectionjson',
        'plugininstances.spectacular_hooks.additionalproperties_for_plugins_instances_create',
    ],

    'SCHEMA_PATH_PREFIX': '/api/v1/',
    # more settings found at:
    # https://drf-spectacular.readthedocs.io/en/latest/settings.html
}
